kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pactbroker-pvc
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      usage: pactbroker-pv